### ISSUE TITLE
Silent install is not silent

### ISSUE THREAD

**Issue by itavero** [groovy/groovy-windows-installer#2]
Running the latest installer (`groovy-2.4.7-installer.exe`) with the arguments `/S /A /N /D=C:\groovy` from an elevated command prompt, still pops up a dialog message halfway though (stating that x64 binaries will be used).
In a silent install, I would not expect such a message.

**Comment by keeganwitt** [comment]
Yep. I forgot to add the default during silent installs.  37aac3f7b3fabefa699ebc909a71e326f7165b65 fixes this.  Thanks for reporting.
