### ISSUE TITLE
GROOVY_HOME is not being set on Windows 10

### ISSUE THREAD

**Issue by itavero** [groovy/groovy-windows-installer#3]
I ran a silent install (`/S /A /N /D=C:\groovy`) and expected the environment `GROOVY_HOME` to be set and added to the path.
Neither of this happened on my Windows 10 machine (did not try another version).

Used `groovy-2.4.7-installer.exe`.

**Comment by itavero** [comment]
Update: I also added the `/V` flag to the arguments, because it was described as `Set Variables` so I figured I might need that as well.

Result was the same: no variables were added/set.

**Comment by keeganwitt** [comment]
It looks like there's a bug with setting GROOVY_HOME with silent installs.  I'll look into it.

**Comment by keeganwitt** [comment]
Sorry for the long turnaround on this.  I believe this is happening because the file associations and environment variable setting is done through custom page functions, and pages don't appear in silent installs.  I'll need to figure out another option for setting these.

**Comment by AlexanderZobkov** [comment]
Hello, 
I can say that /F (file association) switch is not working as well.
Looking into setup.nsi, it looks like non standard NSIS command line switches are not recognized.

**Comment by SikoSoft** [comment]
Still not working.

Installed today, couldn't figure out why my groovy binaries couldn't be found in the shell, despite GROOVY_HOME\bin being in the PATH variable. Upon closer investigation my GROOVY_HOME variable is set to `"C:\PROGRA~2\Groovy\GROOVY~1.0"`

Windows 10 Pro.

Also, I'm not even sure what a "silent install" is. I just installed from the Windows installer binary and this was the result.

**Comment by keeganwitt** [comment]
I'm not sure offhand what went wrong -- I'm on Win10 Pro also and my home got set to C:\PROGRA~2\Groovy\Groovy-2.4.15.

**Comment by keeganwitt** [comment]
As much as NSIS has made things easy for me, I think the best long-term fix for this kind of stuff is to dump NSIS and go to WIX.  That way we can get enterprise installs, system restore points, etc.  In the mean time, I'll keep looking and see if I can figure out what went wrong.

**Comment by SikoSoft** [comment]
It's an easy enough fix to manually correct yourself if you notice what is going wrong. I wasn't sure if it was *literally* what I was seeing or if it was Windows being silly and just truncating it for display.

Perhaps a notice (if there isn't one already) to Windows 10 users is enough somewhere in the doc/readme/install process. Could save you headache from having to devote too much time into this, and you can just wait for enough reports with hard details coming in to paint a clearer picture.

I hope I didn't come off as nagging. I just wanted to mention it still seems to happen.

Thanks for your work on the project! :)

**Comment by keeganwitt** [comment]
Closing, as https://github.com/groovy/groovy-wix is now the replacement for this.
