### ISSUE TITLE
German Umlauts broken on Windows 7

### ISSUE THREAD

**Issue by burka** [groovy/groovy-windows-installer#5]
The Umlauts in the Installer are looking weird.

It looks like the umlauts in [JavaTest.nsi?](https://github.com/groovy/groovy-windows-installer/blob/master/JavaTest.nsi) are not displayed in the right encoding:
![image](https://cloud.githubusercontent.com/assets/283773/24948004/2bdf6c26-1f69-11e7-869d-ad38336f2de1.png)

**Comment by keeganwitt** [comment]
Hmm, you're right.  Thanks for the report.  I'm not sure what's going on yet, there are a umlauts and o umlauts that are displaying correctly in the same nsi file.

**Comment by burka** [comment]
As this hasn't been commented by anyone for almost 5 years the problem seems to be only mine and nobody else cares about it. So better close it :-)

**Comment by burka** [comment]
And thanks for the installer :-)

**Comment by keeganwitt** [comment]
I should probably go back through and closed all the open issues.

I've moved my attention to the MSI-based installer (https://github.com/groovy/groovy-wix). It doesn't yet have any translations, but I'd welcome that contribution.
