### ISSUE TITLE
Installer should be signed

### ISSUE THREAD

**Issue by Vampire** [groovy/groovy-windows-installer#6]
If you download the installer and try to run it, you get a very frightening blue dialogue from Windows, telling you it blocked the installer and you should not run it.
I guess this can be improved if the installer gets signed.

**Comment by keeganwitt** [comment]
I think I should be able to sign it with my personal key using GnuPG.  I'll do some testing to see if that is sufficient to make the warning go away.

**Comment by keeganwitt** [comment]
Update: signing with GnuPG isn't enough to get rid of the warning.  I'm looking into Microsoft's SignTool next.  I think I'll need a certificate from a CA with this tool to make the error go away.

**Comment by Vampire** [comment]
As alternative to the SignTool you can also use jsign.
I successfully signed EXE files with it and it works cross-platform.

**Comment by keeganwitt** [comment]
Closing, as https://github.com/groovy/groovy-wix is now the replacement for this.
