### ISSUE TITLE
NSIS Windows installer is not found

### ISSUE THREAD

**Issue by sudheerkaushik** [groovy/groovy-windows-installer#7]
NSIS Windows installer is not found on http://www.groovy-lang.org/install.html#_installation_on_windows

![groovy-error](https://user-images.githubusercontent.com/8871502/64588731-e58e4a80-d3c0-11e9-9983-fb4601cf2609.PNG)

**Comment by keeganwitt** [comment]
I'm actually not sure where the source for that page is.  I don't see it in https://github.com/apache/groovy-website/.  I'll find out.  Meanwhile, the download button on the top of the page still has working links: https://groovy.apache.org/download.html.

**Comment by keeganwitt** [comment]
Fixed in apache/groovy@2d84eed15f730d2c39a350b4b44ac2db2a162b29 (https://gitbox.apache.org/repos/asf?p=groovy.git;a=commit;h=2d84eed15f730d2c39a350b4b44ac2db2a162b29).
