### ISSUE TITLE
Bintray download link are not found

### ISSUE THREAD

**Issue by krichter722** [groovy/groovy-windows-installer#8]
Opening https://bintray.com/groovy/Distributions/Windows-Installer/view in `README.md` leads to a 404 page. I didn't find the new location.

**Comment by keeganwitt** [comment]
Thanks for pointing this out. Bintray was [shut down](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/), so Groovy disribution moved to  [JFrog](https://groovy.jfrog.io/artifactory/dist-release-local/groovy-windows-installer/). I've updated the README.
I think that URL is easiest to use, but there is also a UI URL you can use: https://groovy.jfrog.io/ui/repos/tree/General/dist-release-local%2Fgroovy-windows-installer.
